name: Download

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Download
      run: |
        wget https://gitlab.com/chenyaofo/dockerfiles/-/raw/main/scripts/download.sh -O run.sh
        bash run.sh
