name: Download

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Download
      run: |
        wget "https://scontent.xx.fbcdn.net/m1/v/t6/An-9xghRwrTBRzIsGXb0NOdR6FCGubZl-oEvlyEBlm0Ez0VdEVO-NQ3gyVXXZWsJ3uyMNiUwEjM7mnhrDiwTS72JQsv5a6k.tar\?ccb\=10-5\&oh\=00_AfCiCX1ub5hie9v7yPSAkMQvVpwxykS586VguV3432XHyg\&oe\=64781CBF\&_nc_sid\=fb0754" -O test.tar
